name: Setup Golang
description: Configures Golang with caching

runs:
  using: "composite"

  steps:
    # uses an older go version by default, so configure go with newest version
    - name: Setup golang
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
      with:
        go-version: '1.24'
        cache: true
