name: Setup Golang
description: Configures Golang with caching

runs:
  using: "composite"

  steps:
    # uses an older go version by default, so configure go with newest version
    - name: Setup golang
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '1.24'
        cache: true
