run:
  modules-download-mode: readonly
  timeout: 10m
issues:
  exclude:
    # Check this issue for more info: https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tc` in function literal
    - Using the variable on range scope `tt` in function literal
linters:
  enable-all: true
  disable:
    # Depreacted linters
    - gomnd
    - execinquery
    - exportloopref
    # Linters to be enabled after fixing the issues
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - goconst
    - godot
    - godox
    - err113
    - gofumpt
    - ireturn
    - lll
    - maintidx
    - mirror
    - nestif
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
    - nlreturn
