version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - goconst
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - mirror
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Using the variable on range scope `tc` in function literal
      - path: (.+)\.go$
        text: Using the variable on range scope `tt` in function literal
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
