#TODO: remove https://dashboard.kyma-project after it's available
external-links-to-ignore: [ "localhost", "kyma.local", "https://dashboard.kyma-project", "https://grafana.kyma.example.com/oauth2/callback", "https://grafana.{DOMAIN", "CLUSTER_NAME.kyma.cluster.cx", "$yourClusterDomain", "svc.cluster.local:8081", "https://goreportcard.com", "orders.com", "azure.microsoft.com", "$KYMA_RELEASE_VERSION", "$DOMAIN", "$LATEST", "http://xip.io", "https://storage.{DOMAIN}/minio", "https://$", "https://commerce-orders-service", "http://azure.com", "https://YOUR_OIDC_COMPLIANT_IDENTITY_PROVIDER_INSTANCE/.well-known/openid-configuration" ]
files-to-ignore: [ "/vendor/", "/testdata/" ]
timeout: 60
request-repeats: 5
files:
  - path: "./.github/ISSUE_TEMPLATE/security-vulnerability.md"
    config:
      internal-links-to-ignore: [ "{CVSS" ]
      external-links-to-ignore: [ "https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N" ]
  - path: "./README.md"
    config:
      external-links-to-ignore: [ "kyma-project.io" ]
