module-name: telemetry-directory-size-exporter
kind: kyma
bdba: []
mend:
  language: golang-mod
  exclude:
      - '**/*_test.go'
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
