module-name: telemetry-directory-size-exporter
kind: kyma
protecode: []
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
      - '**/*_test.go'
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'